### ISSUE TITLE
Always "Translating"

### ISSUE THREAD

**Issue by AkiSakuchan** [raymondmars/chatgpt-chrome-translate-plugin#17]
After selecting some texts and pressing 't', it always says "Translating":
<img width="530" alt="截屏2024-04-05 16 50 20" src="https://github.com/raymondmars/chatgpt-chrome-translate-plugin/assets/83564645/f551d88f-47cc-457f-b1d5-0eea8e107cf5">

**Comment by raymondmars** [comment]
Could you let me know if you configured an API key for it? and confirm you can access OpenAI API.

**Comment by AkiSakuchan** [comment]
> Could you let me know if you configured an API key for it? and confirm you can access OpenAI API.

<img width="592" alt="截屏2024-04-05 17 09 03" src="https://github.com/raymondmars/chatgpt-chrome-translate-plugin/assets/83564645/d5700975-e9b1-44a0-b552-5544b40ae92f">
<img width="969" alt="截屏2024-04-05 17 10 53" src="https://github.com/raymondmars/chatgpt-chrome-translate-plugin/assets/83564645/d3a807e4-89a0-4b83-b51e-98910ea171b5">
In fact, at site of OpenAI, I see that the KEY is used.

**Comment by raymondmars** [comment]
It seems like you come from China. Please confirm you turned on your VPN tool when you use it.
If you can't use a VPN while you use it, you can take this proxy URL(https://common.navitechai.com/v1) to drive it like the screenshot below. Hoping it works for you.
![Snip20240406_16](https://github.com/raymondmars/chatgpt-chrome-translate-plugin/assets/501182/baaf4f60-12ed-436e-88eb-201a3f96433b) 
(**Attention**: we can't assure this proxy URL works forever because of some reasons you sure know in China)

If it doesn't work after you try any solutions, remove this plugin from your Chrome and re-install it from here: https://chromewebstore.google.com/detail/chatgpt-translation-bot/fglemdfemikhijpgojdobdgplbcfomdf

Welcome to give us any feedback after you try.

**Comment by AkiSakuchan** [comment]
No, althought I'm Chinese native speaker, but now I'm in Europe. And I tried to re-install but it doesn't work still.
I assure that OpenAI has received the request from my Chrome, but I dont know why it is always "Translating"

**Comment by raymondmars** [comment]
@AkiSakuchan Can you record a video to show this issue? What happened in the network of the inspection(F12)? Include what OS you are using and the Chrome version. Thank you.

**Comment by AkiSakuchan** [comment]
OK, thanks for your guide. After checking inspection that you say, I find the reason that I dont pay to OpenAI. After paying it, it works bien. Thanks very much.

And I advise that this extension can notice user after getting the message from OpenAI about billing.

**Comment by raymondmars** [comment]
@AkiSakuchan Thank your feedback. I knew why it happened, recently OpenAI changed its API charge policy. for the majority of users need to be pre-paid for using. It was not necessary before. Your advice is great. I will optimize that message.
